language: python

python:
  - "3.6"

sudo: enabled

install:
  - "pip install -r requirements.txt"

services:
  - postgresql

env:
  global:
    - DB_NAME=test_db

before_script:
  - psql -c  'create database test_db;' -U postgres

script: 
  - python -m pytest --cov=app tests/

after-success:
  - coveralls
